USE dbfix360;

INSERT INTO marcas (nombre, tipo) VALUES
('S/M', 'S/M'),
('SHELL HELIX', 'ACEITE'),
('CHEVRON', 'ACEITE'),
('CASTROL', 'ACEITE'),
('MOTUL', 'ACEITE'),
('WILLIAMS', 'ACEITE'),
('REPSOL', 'ACEITE'),
('BARDHAL', 'ACEITE'),
('ALTERNATIVO', 'GENÉRICO'),
('NGK', 'BUJÍAS'),
('BOSCH', 'BUJÍAS'),
('NYLON', 'OTROS'),
('KASUKI', 'OTROS'),
('ALTERNO', 'OTROS'),
('3PK', 'OTROS'),
('LYS', 'FILTROS'),
('MOBIS', 'FILTROS'),
('BLS', 'FILTROS'),
('REDFIL', 'FILTROS'),
('OIL FILTER', 'FILTROS'),
('WANDER', 'FILTROS'),
('KUSA', 'FILTROS'),
('AIR FILTER', 'FILTROS'),
('IHP FILTER', 'FILTROS'),
('IHC', 'OTROS'),
('S6 PLUS', 'OTROS'),
('VISTONY', 'LUBRICANTES'),
('ISHIKAWA', 'FRENOS'),
('NIBK', 'FRENOS'),
('MR POSTERIORES', 'FRENOS'),
('MR DELANTEROS', 'FRENOS'),
('DE FRENO S/M', 'S/M'),
('AUTOLAND', 'OTROS'),
('TOTO', 'OTROS'),
('DE FRENO SDE MANO', 'FRENOS'),
('GOOD YEARS', 'LLANTAS'),
('HYUNDAI I10', 'VEHÍCULOS'),
('KIA', 'VEHÍCULOS'),
('ADEX', 'OTROS'),
('ALMEYDA', 'OTROS'),
('PRESTONE', 'LÍQUIDOS'),
('MEGA GREY', 'OTROS'),
('GMB', 'OTROS'),
('RKD', 'OTROS'),
('JBG', 'OTROS');

INSERT INTO categorias (nombre) VALUES
('ABRAZADERAS'),
('ACEITE'),
('ARANDELA'),
('BOBINA'),
('BUJIAS'),
('CINTILLOS'),
('DISCO'),
('EMPAQUE'),
('FAJA'),
('FILTRO'),
('FOCOS'),
('GRASA'),
('JEBE'),
('JUEGO'),
('KIT'),
('LIQUIDO'),
('LLANTA'),
('ESPEJO'),
('MANGUERA'),
('ORRING'),
('PEGAMENTO'),
('PONCHO'),
('RADIADOR'),
('RECTIFICADORA'),
('REFRIGERANTE'),
('REGULADOR DE ZAPATAS'),
('RESORTES'),
('RETEN'),
('SILICONA'),
('SOPORTE DE CAJA'),
('SUPLEX'),
('TEMPLADOR'),
('TRICETA'),
('VALVULA PCV VALVE');

INSERT INTO subcategorias (idcategoria, nombre) VALUES
(1,'ABRAZADERAS'),
(2,'ACEITE DE MOTOR'),
(3,'ARANDELA'),
(4,'BOBINA DE ENCENDIDO'),
(5,'BUJIAS'),
(6,'CINTILLOS'),
(7,'DISCOS'),
(8,'EMPAQUE'),
(9,'FAJA'),
(10,'FILTRO DE ACEITE'),
(10,'FILTRO DE AIRE'),
(10,'FILTRO DE AIRE ACONDICIONADO'),
(10,'FILTRO DE CABINA'),
(10,'FILTRO DE GASOLINA'),
(10,'FILTRO DE PETROLEO'),
(11,'FOCOS LED'),
(12,'GRASA'),
(13,'JEBES'),
(14,'JUEGO DE PASTILLAS'),
(14,'JUEGO DE ZAPATAS'),
(14,'JUEGO DE PISOS'),
(15,'KIT DE EMPAQUE DE MOTOR'),
(15,'KIT DE ACCESORIOS'),
(16,'LIQUIDO DE FRENO'),
(17,'LLANTA PARA AUTOS'),
(18,'LUNA DE ESPEJO IZQUIERDO'),
(19,'MANGUERA DE BRIDA'),
(19,'MANGUERA DE AGUA'),
(19,'MANGUERA DE RADIADOR DE REVOSE'),
(20,'ORRING'),
(21,'PEGAMENTO'),
(22,'PONCHO'),
(22,'PONCHO DE PALIER'),
(23,'RADIADOR'),
(24,'RECTIFICADORA'),
(25,'REFRIGERANTE PRE MEZCLADO'),
(25,'REFRIGERANTE ANTIFREEZE'),
(26,'REGULADOR DE ZAPATAS'),
(27,'RESORTES'),
(28,'RETEN'),
(29,'SILICONA'),
(30,'SOPORTE DE CAJA'),
(31,'SUPLEX'),
(32,'TEMPLADOR'),
(33,'TRICETA'),
(34,'VALVULA PCV VALVE');

insert into marcas (nombre, tipo) values
('Toyota','vehiculo'),
('Honda','vehiculo'),
('Ford','vehiculo'),
('Hyundai','vehiculo'),
('Chevrolet','vehiculo'),
('Nissan','vehiculo'),
('BMW','vehiculo'),
('Kia','vehiculo'),
('BYD','vehiculo'),
('Audi','vehiculo'),
('BAIC','vehiculo'),
('Briliance','vehiculo'),
('Changan','vehiculo'),
('Chery','vehiculo'),
('Daihatsu','vehiculo');



insert into tipovehiculos (tipov) values 
('Sedan'),
('Hatchback'),
('SUV'),
('Deportivo'),
('Camioneta'),
('Van'),
('Pick up'),
('Convertible'),
('Compacto');

insert into modelos (idtipov,idmarca,modelo) values
(1,1,'ejemplo1'),
(1,2,'ejemplo10'),
(1,3,'ejemplo11'),
(1,4,'ejemplo12'),
(1,5,'ejemplo13'),
(1,6,'ejemplo14'),
(1,7,'ejemplo15'),
(1,8,'ejemplo16'),
(1,9,'ejemplo17'),
(2,1,'ejemplo18'),
(2,2,'ejemplo2'),
(2,3,'ejemplo19'),
(2,4,'ejemplo20'),
(2,5,'ejemplo21'),
(2,6,'ejemplo22'),
(2,7,'ejemplo23'),
(2,8,'ejemplo24'),
(2,9,'ejemplo25'),
(3,1,'ejemplo26'),
(3,2,'ejemplo27'),
(3,3,'ejemplo28'),
(3,4,'ejemplo29'),
(3,5,'ejemplo30'),
(3,6,'ejemplo31'),
(3,7,'ejemplo32'),
(3,8,'ejemplo33'),
(3,9,'ejemplo34'),
(4,1,'ejemplo35'),
(4,2,'ejemplo36'),
(4,3,'ejemplo37'),
(4,4,'ejemplo4'),
(4,5,'ejemplo38'),
(4,6,'ejemplo39'),
(4,7,'ejemplo40'),
(4,8,'ejemplo41'),
(4,9,'ejemplo42'),
(5,1,'ejemplo43'),
(5,2,'ejemplo44'),
(5,3,'ejemplo45'),
(5,4,'ejemplo46'),
(5,5,'ejemplo5'),
(5,6,'ejemplo47'),
(5,7,'ejemplo48'),
(5,8,'ejemplo49'),
(5,9,'ejemplo50'),
(6,1,'ejemplo51'),
(6,2,'ejemplo52'),
(6,3,'ejemplo53'),
(6,4,'ejemplo54'),
(6,5,'ejemplo55'),
(6,6,'ejemplo6'),
(6,7,'ejemplo56'),
(6,8,'ejemplo57'),
(6,9,'ejemplo58'),
(7,1,'ejemplo59'),
(7,2,'ejemplo60'),
(7,3,'ejemplo61'),
(7,4,'ejemplo62'),
(7,5,'ejemplo63'),
(7,6,'ejemplo64'),
(7,7,'ejemplo7'),
(7,8,'ejemplo65'),
(7,9,'ejemplo66'),
(8,1,'ejemplo67'),
(8,2,'ejemplo68'),
(8,3,'ejemplo69'),
(8,4,'ejemplo70'),
(8,5,'ejemplo71'),
(8,6,'ejemplo72'),
(8,7,'ejemplo73'),
(8,8,'ejemplo8'),
(9,1,'ejemplo74'),
(9,2,'ejemplo75'),
(9,3,'ejemplo76'),
(9,4,'ejemplo77'),
(9,5,'ejemplo78'),
(9,6,'ejemplo79'),
(9,7,'ejemplo80'),
(9,8,'ejemplo81'),
(9,9,'ejemplo9');

